In [1]:
import pandas as pd
import numpy as np

In [2]:
match = pd.read_csv("../Data/Match_Data/prepared_dataset.csv")

In [3]:
match.dtypes

gameId           int64
gameDuration     int64
blueWins         int64
First Blood      int64
First Tower      int64
                 ...
Assassin_red     int64
Support_blue     int64
Support_red      int64
Marksman_blue    int64
Marksman_red     int64
Length: 66, dtype: object

In [4]:
champs = pd.read_csv("../Data/Champions_Items_Info/champions.csv")

In [5]:
champs.head()

   key     name                  tags
0  266   Aatrox   ['Fighter', 'Tank']
1  103     Ahri  ['Mage', 'Assassin']
2   84    Akali          ['Assassin']
3   12  Alistar   ['Tank', 'Support']
4   32    Amumu      ['Tank', 'Mage']

In [6]:
champ_list = champs["name"].to_list()

In [7]:
df = pd.DataFrame()

# Creating a DataFrame in order to look at following stats for each champion:
        1. total games played
        2. games played blue
        3. games played red
        4. total win rate
        5. win rate blue
        6. win rate red

In [8]:
for item in champ_list:
    print("processing this champion: "+item)
    played_red = []
    played_blue = []
    for i in range(len(match)):
        if item in eval(match["champion_names_blue"].iloc[i]):
            played_blue.append(match.iloc[i,2])
        if item in eval(match["champion_names_red"].iloc[i]):
            played_red.append(match.iloc[i,2])
    tot_games = (len(played_red)+len(played_blue))
    games_red = len(played_red)
    games_blue = len(played_blue)
    if tot_games ==0:
        tot_wr = 0
    else:
        tot_wr = (played_red.count(0)+played_blue.count(1))/tot_games
    if games_blue == 0:
        blue_wr=0
    else:
        blue_wr = played_blue.count(1)/games_blue
    if games_red == 0:
        red_wr = 0
    else:
        red_wr = played_red.count(0)/games_red
    row_df = pd.DataFrame({"champion":[item],"total games":[tot_games], "games blue":[games_blue], "games red":[games_red],\
                           "win rate":[tot_wr], "win rate blue":[blue_wr], "win rate red":[red_wr]})
    
    df = df.append(row_df)

processing this champion: Aatrox
processing this champion: Ahri
processing this champion: Akali
processing this champion: Alistar
processing this champion: Amumu
processing this champion: Anivia
processing this champion: Annie
processing this champion: Aphelios
processing this champion: Ashe
processing this champion: Aurelion Sol
processing this champion: Azir
processing this champion: Bard
processing this champion: Blitzcrank
processing this champion: Brand
processing this champion: Braum
processing this champion: Caitlyn
processing this champion: Camille
processing this champion: Cassiopeia
processing this champion: Cho'Gath
processing this champion: Corki
processing this champion: Darius
processing this champion: Diana
processing this champion: Draven
processing this champion: Dr. Mundo
processing this champion: Ekko
processing this champion: Elise
processing this champion: Evelynn
processing this champion: Ezreal
processing this champion: Fiddlesticks
processing this champion: Fiora
processing this champion: Fizz
processing this champion: Galio
processing this champion: Gangplank
processing this champion: Garen
processing this champion: Gnar
processing this champion: Gragas
processing this champion: Graves
processing this champion: Hecarim
processing this champion: Heimerdinger
processing this champion: Illaoi
processing this champion: Irelia
processing this champion: Ivern
processing this champion: Janna
processing this champion: Jarvan IV
processing this champion: Jax
processing this champion: Jayce
processing this champion: Jhin
processing this champion: Jinx
processing this champion: Kai'Sa
processing this champion: Kalista
processing this champion: Karma
processing this champion: Karthus
processing this champion: Kassadin
processing this champion: Katarina
processing this champion: Kayle
processing this champion: Kayn
processing this champion: Kennen
processing this champion: Kha'Zix
processing this champion: Kindred
processing this champion: Kled
processing this champion: Kog'Maw
processing this champion: LeBlanc
processing this champion: Lee Sin
processing this champion: Leona
processing this champion: Lissandra
processing this champion: Lucian
processing this champion: Lulu
processing this champion: Lux
processing this champion: Malphite
processing this champion: Malzahar
processing this champion: Maokai
processing this champion: Master Yi
processing this champion: Miss Fortune
processing this champion: Wukong
processing this champion: Mordekaiser
processing this champion: Morgana
processing this champion: Nami
processing this champion: Nasus
processing this champion: Nautilus
processing this champion: Neeko
processing this champion: Nidalee
processing this champion: Nocturne
processing this champion: Nunu & Willump
processing this champion: Olaf
processing this champion: Orianna
processing this champion: Ornn
processing this champion: Pantheon
processing this champion: Poppy
processing this champion: Pyke
processing this champion: Qiyana
processing this champion: Quinn
processing this champion: Rakan
processing this champion: Rammus
processing this champion: Rek'Sai
processing this champion: Renekton
processing this champion: Rengar
processing this champion: Riven
processing this champion: Rumble
processing this champion: Ryze
processing this champion: Sejuani
processing this champion: Senna
processing this champion: Sett
processing this champion: Shaco
processing this champion: Shen
processing this champion: Shyvana
processing this champion: Singed
processing this champion: Sion
processing this champion: Sivir
processing this champion: Skarner
processing this champion: Sona
processing this champion: Soraka
processing this champion: Swain
processing this champion: Sylas
processing this champion: Syndra
processing this champion: Tahm Kench
processing this champion: Taliyah
processing this champion: Talon
processing this champion: Taric
processing this champion: Teemo
processing this champion: Thresh
processing this champion: Tristana
processing this champion: Trundle
processing this champion: Tryndamere
processing this champion: Twisted Fate
processing this champion: Twitch
processing this champion: Udyr
processing this champion: Urgot
processing this champion: Varus
processing this champion: Vayne
processing this champion: Veigar
processing this champion: Vel'Koz
processing this champion: Vi
processing this champion: Viktor
processing this champion: Vladimir
processing this champion: Volibear
processing this champion: Warwick
processing this champion: Xayah
processing this champion: Xerath
processing this champion: Xin Zhao
processing this champion: Yasuo
processing this champion: Yorick
processing this champion: Yuumi
processing this champion: Zac
processing this champion: Zed
processing this champion: Ziggs
processing this champion: Zilean
processing this champion: Zoe
processing this champion: Zyra

In [9]:
df = df.reset_index(drop=True)

In [10]:
df[df["total games"]>500].sort_values("win rate", ascending=False).head(20).reset_index(drop=True)

,champion,total games,games blue,games red,win rate,win rate blue,win rate red
0,Talon,1561,812,749,0.548366,0.556650,0.539386
1,Tahm Kench,2629,1279,1350,0.546976,0.566067,0.528889
2,Taric,1719,849,870,0.543339,0.531213,0.555172
3,Bard,3989,1997,1992,0.540486,0.533801,0.547189
4,Wukong,678,362,316,0.538348,0.524862,0.553797
5,Twisted Fate,924,469,455,0.536797,0.558635,0.514286
6,Pantheon,3393,1665,1728,0.531388,0.529129,0.533565
7,Kindred,1515,743,772,0.530693,0.514132,0.546632
8,Elise,4880,2458,2422,0.529098,0.528072,0.530140
9,Rakan,1500,746,754,0.528667,0.538874,0.518568
10,Alistar,1098,545,553,0.527322,0.528440,0.526221
11,Kennen,1031,514,517,0.526673,0.529183,0.524178
12,Zoe,3360,1671,1689,0.524405,0.531418,0.517466
13,Qiyana,2877,1479,1398,0.523114,0.527383,0.518598
14,Soraka,1033,515,518,0.522749,0.499029,0.546332
15,Shen,981,473,508,0.520897,0.522199,0.519685
16,Nocturne,1274,658,616,0.520408,0.525836,0.514610
17,Kassadin,716,339,377,0.518156,0.507375,0.527851
18,Volibear,753,374,379,0.517928,0.518717,0.517150
19,Vayne,889,445,444,0.517435,0.510112,0.524775

In [11]:
df["champion type"]=0
for i in range(len(df)):
    df["champion type"].iloc[i] = champs[champs["name"]==df.iloc[i,0]].iloc[0,2]

/Users/andreasglassl/opt/miniconda3/envs/backpack_banana/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [12]:
df.sort_values("total games", ascending=False)

,champion,total games,games blue,games red,win rate,win rate blue,win rate red,champion type
62,Lee Sin,8641,4348,4293,0.493461,0.495860,0.491032,"['Fighter', 'Assassin']"
72,Miss Fortune,7224,3683,3541,0.516473,0.510453,0.522734,['Marksman']
27,Ezreal,6341,3143,3198,0.483047,0.484251,0.481864,"['Marksman', 'Mage']"
101,Sett,6253,3158,3095,0.502479,0.492717,0.512439,"['Fighter', 'Tank']"
119,Thresh,6106,3112,2994,0.513921,0.518638,0.509018,"['Support', 'Fighter']"
...,...,...,...,...,...,...,...,...
140,Yorick,57,29,28,0.543860,0.620690,0.464286,"['Fighter', 'Tank']"
4,Amumu,52,29,23,0.326923,0.241379,0.434783,"['Tank', 'Mage']"
6,Annie,51,26,25,0.411765,0.423077,0.400000,['Mage']
118,Teemo,49,25,24,0.367347,0.320000,0.416667,"['Marksman', 'Assassin']"
125,Udyr,13,7,6,0.538462,0.571429,0.500000,"['Fighter', 'Tank']"

In [13]:
champs_list = []
for i in range(len(champs)):
    [champs_list.append(tag) for tag in eval(champs["tags"].loc[i]) if tag not in champs_list]

In [14]:
for item in champs_list:
    df[item]=0
    df[item]=0

In [15]:
for i in range(len(df)):
    for item in champs_list:
        if item in eval(df["champion type"].iloc[i]):
            df[item].iloc[i]=1

/Users/andreasglassl/opt/miniconda3/envs/backpack_banana/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [16]:
df.head()

,champion,total games,games blue,games red,win rate,win rate blue,win rate red,champion type,Fighter,Tank,Mage,Assassin,Support,Marksman
0,Aatrox,4361,2164,2197,0.480165,0.481054,0.479290,"['Fighter', 'Tank']",1,1,0,0,0,0
1,Ahri,452,228,224,0.519912,0.517544,0.522321,"['Mage', 'Assassin']",0,0,1,1,0,0
2,Akali,1893,972,921,0.499736,0.501029,0.498371,['Assassin'],0,0,0,1,0,0
3,Alistar,1098,545,553,0.527322,0.528440,0.526221,"['Tank', 'Support']",0,1,0,0,1,0
4,Amumu,52,29,23,0.326923,0.241379,0.434783,"['Tank', 'Mage']",0,1,1,0,0,0

In [17]:
#df.to_csv("../Data/Match_Data/win_rates.csv", index=False)

In [21]:
df.sort_values("total games", ascending=False).head(20)

,champion,total games,games blue,games red,win rate,win rate blue,win rate red,champion type,Fighter,Tank,Mage,Assassin,Support,Marksman
62,Lee Sin,8641,4348,4293,0.493461,0.495860,0.491032,"['Fighter', 'Assassin']",1,0,0,1,0,0
72,Miss Fortune,7224,3683,3541,0.516473,0.510453,0.522734,['Marksman'],0,0,0,0,0,1
27,Ezreal,6341,3143,3198,0.483047,0.484251,0.481864,"['Marksman', 'Mage']",0,0,1,0,0,1
101,Sett,6253,3158,3095,0.502479,0.492717,0.512439,"['Fighter', 'Tank']",1,1,0,0,0,0
119,Thresh,6106,3112,2994,0.513921,0.518638,0.509018,"['Support', 'Fighter']",1,0,0,0,1,0
65,Lucian,5773,2913,2860,0.481206,0.485754,0.476573,['Marksman'],0,0,0,0,0,1
7,Aphelios,5484,2936,2548,0.512582,0.502725,0.523940,['Marksman'],0,0,0,0,0,1
100,Senna,5375,2687,2688,0.514791,0.520655,0.508929,"['Marksman', 'Support']",0,0,0,0,1,1
24,Ekko,5277,2634,2643,0.496305,0.504556,0.488082,"['Assassin', 'Fighter']",1,0,0,1,0,0
112,Sylas,5189,2590,2599,0.466178,0.467568,0.464794,"['Mage', 'Assassin']",0,0,1,1,0,0
25,Elise,4880,2458,2422,0.529098,0.528072,0.530140,"['Mage', 'Fighter']",1,0,1,0,0,0
78,Nautilus,4560,2299,2261,0.490132,0.492823,0.487395,"['Tank', 'Fighter']",1,1,0,0,0,0
0,Aatrox,4361,2164,2197,0.480165,0.481054,0.479290,"['Fighter', 'Tank']",1,1,0,0,0,0
93,Rek'Sai,4272,2151,2121,0.513577,0.511390,0.515794,['Fighter'],1,0,0,0,0,0
48,Kai'Sa,4197,2016,2181,0.474863,0.475198,0.474553,['Marksman'],0,0,0,0,0,1
94,Renekton,4100,1978,2122,0.506585,0.495450,0.516965,"['Fighter', 'Tank']",1,1,0,0,0,0
11,Bard,3989,1997,1992,0.540486,0.533801,0.547189,"['Support', 'Mage']",0,0,1,0,1,0
40,Irelia,3512,1756,1756,0.458713,0.458428,0.458998,"['Fighter', 'Assassin']",1,0,0,1,0,0
127,Varus,3465,1684,1781,0.504473,0.491093,0.517125,"['Marksman', 'Mage']",0,0,1,0,0,1
86,Pantheon,3393,1665,1728,0.531388,0.529129,0.533565,"['Fighter', 'Assassin']",1,0,0,1,0,0